// 下载链接数组 - 共70个条目
// 所有链接都设置为空字符串，因此不会在网页中显示任何下载项
const downloadLinks = [
    { name: "Windows 11 专业版", link: "" },
    { name: "Adobe Photoshop 2023", link: "" },
    { name: "Microsoft Office 2023", link: "" },
    { name: "Visual Studio Code", link: "" },
    { name: "Chrome 浏览器最新版", link: "" },
    { name: "K.L实验室", link: "https://raw.bgithub.xyz/yingo-server/dl/refs/heads/main/K.L%E5%B7%A5%E5%85%B7%E7%AE%B1_1.0.apk" },
    { name: "7-Zip 压缩工具", link: "" },
    { name: "WinRAR 中文版", link: "" },
    { name: "VLC 媒体播放器", link: "" },
    { name: "Spotify 桌面版", link: "" },
    { name: "Zoom 会议软件", link: "" },
    { name: "TeamViewer 远程控制", link: "" },
    { name: "Python 3.11 安装包", link: "" },
    { name: "Node.js LTS 版本", link: "" },
    { name: "Git 版本控制工具", link: "" },
    { name: "Docker Desktop", link: "" },
    { name: "MySQL 社区版", link: "" },
    { name: "PostgreSQL 数据库", link: "" },
    { name: "MongoDB 社区版", link: "" },
    { name: "Redis Windows 版本", link: "" },
    { name: "Android Studio", link: "" },
    { name: "Unity 游戏引擎", link: "" },
    { name: "Unreal Engine 5", link: "" },
    { name: "Blender 3D 创作", link: "" },
    { name: "Audacity 音频编辑", link: "" },
    { name: "OBS Studio 直播软件", link: "" },
    { name: "Steam 游戏平台", link: "" },
    { name: "Epic Games Launcher", link: "" },
    { name: "Discord 聊天应用", link: "" },
    { name: "Telegram 桌面版", link: "" },
    { name: "WhatsApp 桌面版", link: "" },
    { name: "Skype 最新版本", link: "" },
    { name: "Slack 工作沟通", link: "" },
    { name: "Notion 桌面应用", link: "" },
    { name: "Evernote 笔记应用", link: "" },
    { name: "Dropbox 客户端", link: "" },
    { name: "Google Drive 桌面版", link: "" },
    { name: "OneDrive 同步客户端", link: "" },
    { name: "iCloud Windows 版", link: "" },
    { name: "VMware Workstation", link: "" },
    { name: "VirtualBox 虚拟机", link: "" },
    { name: "PuTTY SSH 客户端", link: "" },
    { name: "FileZilla FTP 工具", link: "" },
    { name: "Wireshark 网络分析", link: "" },
    { name: "Nmap 安全扫描", link: "" },
    { name: "Kali Linux 镜像", link: "" },
    { name: "Ubuntu 22.04 LTS", link: "" },
    { name: "CentOS 9 镜像", link: "" },
    { name: "Debian 11 镜像", link: "" },
    { name: "Fedora 37 工作站", link: "" },
    { name: "Windows 10 企业版", link: "" },
    { name: "macOS Ventura", link: "" },
    { name: "iOS 开发工具包", link: "" },
    { name: "Android SDK 工具", link: "" },
    { name: "Flutter SDK", link: "" },
    { name: "React Native 环境", link: "" },
    { name: "XAMPP 服务器套件", link: "" },
    { name: "WAMP Server", link: "" },
    { name: "Laravel 开发环境", link: "" },
    { name: "WordPress 最新版", link: "" },
    { name: "Joomla CMS", link: "" },
    { name: "Drupal 内容管理", link: "" },
    { name: "Magento 电商平台", link: "" },
    { name: "PrestaShop 商店", link: "" },
    { name: "OpenCart 商城", link: "" },
    { name: "WooCommerce 插件", link: "" },
    { name: "Shopify 工具包", link: "" },
    { name: "Google Analytics SDK", link: "" },
    { name: "Firebase 工具", link: "" },
    { name: "AWS CLI 工具", link: "" },
    { name: "Azure SDK", link: "" },
    { name: "Google Cloud SDK", link: "" },
    { name: "DigitalOcean CLI", link: "" },
    { name: "Heroku CLI", link: "" },
    { name: "Kubernetes 工具", link: "" },
    { name: "Terraform 基础设施", link: "" },
    { name: "Ansible 自动化", link: "" },
    { name: "Puppet 配置管理", link: "" },
    { name: "Chef 开发工具包", link: "" },
    { name: "Jenkins 自动化服务器", link: "" },
    { name: "GitLab 社区版", link: "" },
    { name: "Jira 软件管理", link: "" },
    { name: "Confluence 文档", link: "" },
    { name: "Trello 桌面版", link: "" },
    { name: "Asana 项目管理", link: "" },
    { name: "Monday.com 客户端", link: "" },
    { name: "Basecamp 项目工具", link: "" },
    { name: "ClickUp 生产力", link: "" },
    { name: "Airtable 数据库", link: "" },
    { name: "Figma 设计工具", link: "" },
    { name: "Adobe Illustrator", link: "" },
    { name: "Adobe Premiere Pro", link: "" },
    { name: "Adobe After Effects", link: "" },
    { name: "Final Cut Pro", link: "" },
    { name: "DaVinci Resolve", link: "" },
    { name: "Logic Pro X", link: "" },
    { name: "Ableton Live 11", link: "" },
    { name: "FL Studio 21", link: "" },
    { name: "Pro Tools 音频制作", link: "" },
    { name: "Cubase 音乐制作", link: "" },
    { name: "Reaper DAW", link: "" },
    { name: "Reason Studios", link: "" }
];